#!/usr/bin/python3

import roslaunch
import rospy
from map_switcher.change_maps import MapSwitcher

if __name__ == '__main__':
    rospy.init_node('map_switcher', anonymous=True)

    # switcher = MapSwitcher('$(find map_switcher)/config/')
    switcher = MapSwitcher('/nav/maps/config/')

    rospy.spin()
